apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCBLc1/RSE1CUm4aRtGdQsQ3sSyK0RFTF3hSlF4GL/OTICdhaMjroW2aWhQNuMnwFPwFKMTriVjF0URC7Gpo5y12ZjTKXig1ZYy/CrNOP5MocE4dTfHe+btOBZeKYBn+KY2fr6fvStYBp4oZ9bkHeFEvRe/vpMLak14Kue5/JIS7i4XSdSPGY+SFgKoxqR7C1M8uvoLJR/ADT9E6HM2KPW5ND/2zPkzUIZmZC1eFBCHwuYRBvPMEiPUXV4I6XxsXo/ZseSVQMpnDv6hMzL4jg1OT48UHeFBNrMVg3xKqEFsXIGGwBjMvsw97poKcvh+oE2CUYegcqCSMF6DvBTlDI580spMtoSYPWBwNIA9tySdTErC8bgX7M381wNT0skzN4yinGZVfyAcMuo2JLkc2xBXTK9IDIXd3dWbltpaflvjvViQ1DZTt1LNV1DrIRHsMlJy24DtFUSrYcCBmkK1PyF9ngcAPh7/nKFq2BNOFUQb+uq6IpTVSLvonwFmSjynE+Z/uHZC1lO2X+Cp4WKb7cL+zuqdqaQjyCkZumQ32twQH2lLCvsWqtU1BJc6CM6gO8rCxGROgceQbcKWTaBJcoOfEu0rPc6f5w5tzaDc5X4nCmfLScKo6i9HiNdpqDL5U4eF1iE2StloxNUfBPBlbokFkUag9kKmSFYQNCECi2JZFOPJ4qN2JKC5UFPNnF1VP2sEc9Gx2ggcIytVoPC/mF2efChiJ2w1YZB37f4gkQoMZC5wncP+M/OLOQ053C3tPw5+bCA3VS3fn3/ZT5Liuv64TjwNLWYDeF6U1kRqYfLwvwJitw/LUyBcVoCGmG3pjAm/HZb6MYvm5SrulSW1pVDLFzk/FN+qfuN68XwL6uYtMhkwwE1Abpfcr6lUlysLngRuEBtspgLqrlVWobFLCp2Irgw=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

