#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: argo-workflows
#  namespace: argo
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
#spec:
#  project: production
#  source:
#    path: argo-workflows/overlays/production
#    repoURL: https://github.com/gbulanov/argo-combined-demo
#    targetRevision: HEAD
#  destination:
#    server: https://kubernetes.default.svc
#  syncPolicy:
#    automated:
#      selfHeal: true
#      prune: true

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    repoURL: 'https://github.com/argoproj/argo-helm.git'
    path: charts/argo-workflows
    targetRevision: HEAD
    helm:
      parameters:
        - name: server.ingress.enabled
          value: 'true'
        - name: server.ingress.ingressClassName
          value: nginx
        - name: server.ingress.hosts
          value: argo-workflows.dev-ops-experiments.eu-west-2.fdp-infra.fredhopper.com
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
