apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    repoURL: 'https://github.com/grafana/helm-charts.git'
    path: charts/loki-stack
    targetRevision: HEAD
    helm:
      parameters:
        - name: grafana.enabled
          value: 'true'
        - name: prometheus.enabled
          value: 'true'
        - name: loki.enabled
          value: 'true'
        - name: promtail.enabled
          value: 'true'
        - name: prometheus.alertmanager.persistentVolume.enabled
          value: 'true'
        - name: prometheus.server.persistentVolume.enabled
          value: 'true'
        - name: loki.persistence.enabled
          value: 'true'
        - name: loki.persistence.storageClassName
          value: 'standard'
        - name: loki.persistence.size
          value: '5Gi'
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
