apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-3tier-app2-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: api/kustomize/overlays/production
    repoURL: https://github.com/gbulanov/node-3tier-app.git
    targetRevision: HEAD
    kustomize:
      images:
      - gbulanov/node-3tier-app2-api:latest
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
